Repository maya-manager/server, pull requests merged in 2023-06, with the labels that each got.

#5 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#11 docs: added issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/security_issue.yml
  .github/ISSUE_TEMPLATE/test.yml
  README.md
Labels: documentation

#34 docs: Update `README.md`
  README.md
Labels: documentation

#36 ci: workflow for deploying docs
  .github/workflows/deploy-docs.yml
Labels: CI/CD

#37 docs: section in readme for tech stack
  README.md
Labels: documentation

#65 feat: added request logging
  package.json
  src/app.module.ts
  src/middleware/requestLogger.middleware.ts
Labels: enhancement
